name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with MSVC
        # Visual Studio est déjà présent sur le runner Windows.
        # On invoque cl.exe directement.
        run: |
          cl /EHsc /nologo /std:c++17 /O2 chrome_decrypt.cpp /link /OUT:chrome_decrypt.exe

      - name: Upload artifact
        # Utilisez une version précise pour éviter les problèmes de résolution
        uses: actions/upload-artifact@v3.1.2
        with:
          name: chrome_decrypt
          path: chrome_decrypt.exe
