name: Windows Build (MinGW)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2 (MinGW)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc
          path-type: inherit

      - name: Build with g++
        run: |
          # Compile en statique (-static) pour générer un exécutable autonome
          g++ -std=c++17 -O2 -static -o chrome_decrypt.exe chrome_decrypt.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: chrome_decrypt
          path: chrome_decrypt.exe
