name: Build and Download .exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile with cl.exe
        run: |
          cl /EHsc chrome_decrypt.cpp oleaut32.lib shell32.lib advapi32.lib shlwapi.lib ^
            /link /OUT:chrome_decrypt.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: chrome_decrypt.exe
          path: chrome_decrypt.exe
