name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure MSVC environment
        # Sur l'image windows-latest, Visual Studio est déjà installé
        # Vous pouvez donc directement invoquer `cl`.
        run: |
          echo "Configuration de l'environnement MSVC"

      - name: Build with MSVC
        run: |
          cl /EHsc /nologo /std:c++17 /O2 ChromeAppBoundDecrypt.cpp /link /OUT:ChromeAppBoundDecrypt.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ChromeAppBoundDecrypt
          path: ChromeAppBoundDecrypt.exe
