name: Build and Download .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Upload executable
        uses: actions/upload-pages-artifact@v3
        with:
          name: chrome_decrypt.exe
          path: build/Release/chrome_decrypt.exe
